### ISSUE TITLE
minSdk chang d to 23?

### ISSUE THREAD

**Issue by treysis** [ApturiCOVID/apturicovid-android#3]
An earlier version of the app only required minSdk=21. The current version requires minSdk=23. Why was this changed? Can we find APK with minSdk=21 somewhere for Android 5 phones? My Android 5 phone shows that contact tracing API is available.

**Comment by edgarsMalahovskis** [comment]
Hi!
Unfortunately Exposure Notification API is available only starting from Android 6.0 (SDK 23). You can get more extensive information here: https://developers.google.com/android/exposure-notifications/exposure-notifications-api

**Comment by treysis** [comment]
I know. But the reference implementation uses SDK 21?! And your previous version .36 used SDK 21, but now version .47 is using SDK 23. I tried to sideload .36, but it seems your app uses sideload protection (I cannot install it neither on Android 9, nor Android 5).

I was actually wondering if this really works on Android 5 as this is the reference implementation. I know everyone is writing SDK 23 / Android 6, but it would be interesting to see if this is just an arbitrary limitation.

**Comment by edgarsMalahovskis** [comment]
It is not an arbitrary limitation. Version .36 was indeed built with minSdk 21, but soon enough we realised that not a single Android 5 device is capable of using our app, thus latest version is not supporting sdk 21.

**Comment by treysis** [comment]
I know this is only a theoretical discussion, so thank you for your time. But would you mind explaining what happened with Android 5 devices? Because if I open PlayServices on my Android 5 phone, I can see the option for "COVID-19 Exposure Notifications".
I'd love to try myself, but obviously I am not a whitelisted developer.

**Comment by edgarsMalahovskis** [comment]
As of my knowledge, Android 5 was never intended to be supported. Unfortunately, I don’t have enough information on why there are some misleading settings on Android 5, sorry.

**Comment by treysis** [comment]
Hm, but SDK 21 was also in the reference app by Google.
